FROM node:lts-alpine

ARG MODE
# Install simple HTTP server for serving static content
RUN npm install -g http-server

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install -g http-server --timeout=60000

# Copy project files and folders to the current working directory
COPY . .

# Build the app with the specified mode
RUN npm run build -- --mode ${MODE}

# Expose port 8080
EXPOSE 8080

# Start the HTTP server to serve the built app
CMD ["http-server", "dist"]
