name: ie-bank-frontend

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          npm install
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            npm run build -- --mode development --dest dist-dev
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npm run build -- --mode uat --dest dist-uat
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref == 'refs/heads/dev' && 'node-app-dev' || 'node-app-uat' }}
          path: ${{ github.ref == 'refs/heads/dev' && 'dist-dev/' || 'dist-uat/' }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main' || github.ref == 'refs/heads/main' && 'UAT' || 'Development' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref == 'refs/heads/main' && 'node-app-uat' || 'node-app-dev' }}

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ github.ref == 'refs/heads/main' && 'adelatorre-frontend-uat' || 'adelatorre-frontend-dev' }}
          package: .