name: ie-bank-frontend

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          npm install
          npm run build -- --mode uat --dest dist-uat

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App Frontend UAT'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'adelatorre-frontend-uat'
          package: .
